module.exports = {
  таб: ['tab'],
  тап: ['tab'],
  контрол: ['control'],
  альт: ['alt'],
  скейт: ['escape'],
  alt: ['alt'],
  tab: ['tab'],
  tap: ['tap'],
  энтер: ['enter'],
  отправь: ['enter'],
  отправить: ['enter'],
  стереть: ['backspace'],
  пробел: ['space'],
  ескейп: ['escape'],
  вправо: ['right'],
  влево: ['left'],
  вверх: ['up'],
  вниз: ['down'],
  enter: ['enter'],
  control: ['control'],
  escape: ['escape'],
  'выделить всё': ['a', ['control']],
  'выделить все': ['a', ['control']],
  'выделить слово': ['left', ['control', 'shift']],
  'стереть слово': ['backspace', ['control']],
  вставить: ['v', ['control']],
  вырезать: ['x', ['control']],
  копировать: ['c', ['control']],
  отменить: ['z', ['control']],
  'закрой вкладку': ['w', ['control']],
  'новая вкладка': ['t', ['control']],
  'следующая вкладка': ['tab', ['control']],
  'восстанови вкладку': ['t', ['control', 'shift']],
}
